### ISSUE TITLE
Help needed to assign a list of users for a course

### ISSUE THREAD

**Issue by jinskrish** [charliequinn/python-litmos-api#3]
Hi Charlie,
I am unable to go beyond the code mentioned below

litmos = Litmos({'aXXXXXXXXXXXXX'},{'https://api.litmoseu.com/v1.svc'})

Is there anyway I could directly get the Json file downloaded. Or derive a code to assign course to a list of users 

Thanks in advance.

Regards,
Jins

**Comment by charliequinn** [comment]
Hi Jins, apologies it's a mistake in the README it should be

`litmos = Litmos('aXXXXXXXXXXXXX', 'https://api.litmoseu.com/v1.svc')`

**Comment by charliequinn** [comment]
Hi Jins,

If you update to latest version 0.6.2 and follow the updated instructions on README (Getting Started) you should be good.

```from litmos import Litmos


API_KEY = 'AXXXXXXXXXX'
LITMOS_APP_NAME = 'jins.litmos.com'
LITMOS_SERVER_URL = 'https://api.litmos.com/v1.svc'  # https://support.litmos.com/hc/en-us/articles/227734667-Overview-Developer-API
litmos = Litmos(API_KEY, LITMOS_APP_NAME, LITMOS_SERVER_URL)```
