### ISSUE TITLE
Data format - Incomprehensible 

### ISSUE THREAD

**Issue by jinskrish** [charliequinn/python-litmos-api#5]
Hey Charlie,

I was able to sync the API in python however the data fetched is in the format which doesn't match the records. For example: The user id is numeric and the output I get is "0x02FEB4F0"

Am I missing something here?

Regards,
Jins V

**Comment by charliequinn** [comment]
Hi Jins,

Apologies for not seeing this issue sooner. Are you still having it? If so, can you send me as much info about your python environment (python version and the output from pip freeze?
